import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, ArrowRight, Check, Camera, Upload, Sparkles, MapPin } from "lucide-react";
import { useMemo, useState } from "react";

const steps = ["Welcome", "Your craft", "Your identity", "Your work", "Experience", "Strengths", "Availability", "Ready"];
const crafts = ["Actor", "Director", "Cinematographer", "Editor", "Singer", "Musician", "Writer", "Dancer", "VFX Artist", "Sound Designer"];
const strengthsList = ["Feature Film", "Short Film", "Commercial", "Documentary", "Theatre", "Music Video", "Independent", "Studio"];

const Field = ({ label, value, onChange, placeholder }) => (
  <label className="block"><span className="mb-2 block text-[10px] uppercase tracking-[.22em] text-neutral-500">{label}</span><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="w-full border-b border-white/10 bg-transparent py-3 text-lg text-white outline-none placeholder:text-neutral-700 focus:border-amber-400/60" /></label>
);
const Screen = ({ children }) => <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -14 }} transition={{ duration: .35, ease: [0.22, 1, .36, 1] }} className="mx-auto w-full max-w-5xl px-5 pb-32 pt-20 sm:px-8 lg:px-12">{children}</motion.div>;

export default function TalentOnboarding() {
  const [i, setI] = useState(0), [craft, setCraft] = useState(""), [name, setName] = useState(""), [professionalName, setProfessionalName] = useState(""), [city, setCity] = useState(""), [skills, setSkills] = useState([]), [availability, setAvailability] = useState("available"), [uploaded, setUploaded] = useState(false), [credits, setCredits] = useState(0);
  const strength = useMemo(() => Math.min(100, 15 + (craft ? 15 : 0) + (name ? 15 : 0) + (city ? 10 : 0) + (uploaded ? 20 : 0) + (credits ? 10 : 0) + (skills.length ? 10 : 0) + (availability ? 5 : 0)), [craft, name, city, uploaded, credits, skills, availability]);
  const next = () => setI(x => Math.min(7, x + 1)), back = () => setI(x => Math.max(0, x - 1));
  const screens = [
    <Screen key="welcome"><div className="grid min-h-[70vh] items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">01 · YOUR JOURNEY</p><h1 className="mt-5 text-5xl font-medium leading-[.95] tracking-[-.04em] text-white sm:text-7xl">Your work deserves to be discovered.</h1><p className="mt-7 max-w-xl text-base leading-7 text-neutral-500 sm:text-lg">Let&apos;s build a profile that puts your craft, your work, and your experience in front of the right people.</p><button onClick={next} className="mt-10 inline-flex items-center gap-3 rounded-full bg-amber-400 px-6 py-3 text-sm font-medium text-black transition-[gap,transform] hover:gap-4 hover:-translate-y-0.5">Start my profile <ArrowRight size={16}/></button><p className="mt-4 text-[10px] text-neutral-700">You can save your progress and come back anytime.</p></div><div className="relative aspect-[4/5] overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_50%_30%,rgba(245,158,11,.18),transparent_32%),linear-gradient(145deg,#18120a,#070707_70%)]"><motion.div animate={{scale:[1,1.04,1],opacity:[.45,.8,.45]}} transition={{duration:5,repeat:Infinity,ease:"easeInOut"}} className="absolute left-1/2 top-1/2 h-40 w-40 -translate-x-1/2 -translate-y-1/2 rounded-full border border-amber-400/30 shadow-[0_0_100px_rgba(245,158,11,.12)]"/><div className="absolute bottom-8 left-8 right-8 border-t border-white/[.08] pt-4"><p className="text-[8px] uppercase tracking-[.25em] text-amber-400">PRE PRO POST</p><p className="mt-2 text-sm text-white">Make the work the introduction.</p></div></div></div></Screen>,
    <Screen key="craft"><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">02 · YOUR CRAFT</p><h2 className="mt-4 text-4xl font-medium text-white sm:text-6xl">What do you do?</h2><p className="mt-4 text-neutral-500">Choose the craft you want people to discover you for.</p><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{crafts.map((x,n)=><button key={x} onClick={()=>setCraft(x)} className={`rounded-2xl border p-5 text-left transition ${craft===x?"border-amber-400/50 bg-amber-400/[.07]":"border-white/[.08] bg-white/[.015] hover:border-white/20"}`}><span className="text-[9px] text-neutral-700">0{n+1}</span><p className="mt-5 text-base text-white">{x}</p>{craft===x&&<Check size={16} className="mt-4 text-amber-400"/>}</button>)}</div></Screen>,
    <Screen key="identity"><div className="max-w-2xl"><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">03 · YOUR IDENTITY</p><h2 className="mt-4 text-4xl font-medium text-white sm:text-6xl">Tell us who you are.</h2><p className="mt-4 text-neutral-500">Keep it simple. You can refine your profile later.</p><div className="mt-12 space-y-8"><Field label="Your name" value={name} onChange={setName} placeholder="Your full name"/><Field label="Professional name" value={professionalName} onChange={setProfessionalName} placeholder="How you&apos;d like to be known"/><Field label="City" value={city} onChange={setCity} placeholder="Hyderabad"/></div><div className="mt-12 flex items-center gap-4 rounded-2xl border border-white/[.08] p-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-white/[.04]"><Camera size={18} className="text-neutral-500"/></div><div><p className="text-sm text-white">Add a profile photo later</p><p className="mt-1 text-xs text-neutral-600">A clear photo helps people remember you.</p></div></div></div></Screen>,
    <Screen key="work"><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">04 · YOUR WORK</p><h2 className="mt-4 text-4xl font-medium text-white sm:text-6xl">Show us what you&apos;ve made.</h2><p className="mt-4 text-neutral-500">Your work is the strongest introduction.</p><button onClick={()=>setUploaded(true)} className="mt-12 flex min-h-72 w-full flex-col items-center justify-center rounded-[2rem] border border-dashed border-white/15 bg-white/[.015] hover:border-amber-400/40">{uploaded?<><Check size={30} className="text-amber-400"/><p className="mt-4 text-white">Your first work sample is ready.</p></>:<><Upload size={30} className="text-neutral-600"/><p className="mt-4 text-white">Add your first work sample</p><p className="mt-2 text-xs text-neutral-600">Video, audio, image, or reel</p></>}</button></Screen>,
    <Screen key="experience"><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">05 · EXPERIENCE</p><h2 className="mt-4 text-4xl font-medium text-white sm:text-6xl">What have you worked on?</h2><p className="mt-4 text-neutral-500">Add credits when you have them. New to the industry? You can skip this.</p><div className="mt-12 rounded-[2rem] border border-white/[.08] p-6 sm:p-8"><p className="text-sm text-white">Project credits</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-white/[.06] p-4 text-neutral-600">Project</div><div className="rounded-xl border border-white/[.06] p-4 text-neutral-600">Role</div><div className="rounded-xl border border-white/[.06] p-4 text-neutral-600">Year</div></div><button onClick={()=>setCredits(x=>x+1)} className="mt-6 text-sm text-amber-400">+ Add a credit</button>{credits>0&&<div className="mt-6 rounded-xl border border-amber-400/15 bg-amber-400/[.04] p-4 text-sm text-white">{credits} credit added</div>}</div></Screen>,
    <Screen key="strengths"><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">06 · YOUR STRENGTHS</p><h2 className="mt-4 text-4xl font-medium text-white sm:text-6xl">What should people know?</h2><p className="mt-4 text-neutral-500">Pick the strengths that best describe your work.</p><div className="mt-10 flex flex-wrap gap-3">{strengthsList.map(x=><button key={x} onClick={()=>setSkills(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])} className={`rounded-full border px-5 py-3 text-sm ${skills.includes(x)?"border-amber-400/50 bg-amber-400/[.08] text-amber-300":"border-white/10 text-neutral-400"}`}>{x}</button>)}</div></Screen>,
    <Screen key="availability"><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">07 · AVAILABILITY</p><h2 className="mt-4 text-4xl font-medium text-white sm:text-6xl">When can you work?</h2><p className="mt-4 text-neutral-500">This helps recruiters find talent who can actually take the project.</p><div className="mt-10 grid gap-3 sm:grid-cols-3">{[["available","Available now"],["later","Available soon"],["unavailable","Not available"]].map(([id,label])=><button key={id} onClick={()=>setAvailability(id)} className={`rounded-2xl border p-5 text-left ${availability===id?"border-amber-400/50 bg-amber-400/[.07]":"border-white/[.08]"}`}><p className="text-sm text-white">{label}</p><p className="mt-2 text-xs text-neutral-600">Recruiters can see this.</p></button>)}</div><div className="mt-10 rounded-2xl border border-white/[.08] p-5"><div className="flex items-center gap-3"><MapPin size={16} className="text-amber-400"/><p className="text-sm text-white">{city||"Your location"}</p></div></div></Screen>,
    <Screen key="ready"><div className="mx-auto max-w-3xl text-center"><p className="text-[10px] uppercase tracking-[.3em] text-amber-400">08 · READY</p><motion.div initial={{scale:.85,opacity:0}} animate={{scale:1,opacity:1}} className="mx-auto mt-8 flex h-36 w-36 items-center justify-center rounded-full border border-amber-400/30 bg-amber-400/[.04] shadow-[0_0_100px_rgba(245,158,11,.12)]"><div><Sparkles className="mx-auto text-amber-400" size={24}/><p className="mt-2 text-3xl font-medium text-white">{strength}%</p></div></motion.div><h2 className="mt-10 text-4xl font-medium text-white sm:text-6xl">You&apos;re ready to be discovered.</h2><p className="mx-auto mt-5 max-w-xl text-neutral-500">Your profile is becoming a professional introduction to your work. Keep adding to it as your journey grows.</p><button className="mt-10 inline-flex items-center gap-3 rounded-full bg-amber-400 px-6 py-3 text-sm font-medium text-black">Enter Talent Network <ArrowRight size={16}/></button></div></Screen>
  ];
  return <main className="min-h-screen bg-[#060606] text-white"><div className="fixed left-0 right-0 top-0 z-50 h-1 bg-white/[.05]"><motion.div className="h-full bg-amber-400" animate={{width:`${((i+1)/8)*100}%`}}/></div><div className="pointer-events-none fixed inset-0 opacity-[.035] [background-image:radial-gradient(rgba(255,255,255,.8)_0.5px,transparent_.5px)] [background-size:4px_4px]"/><AnimatePresence mode="wait">{screens[i]}</AnimatePresence><div className="fixed bottom-0 left-0 right-0 z-40 border-t border-white/[.06] bg-[#060606]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><button onClick={back} disabled={!i} className="inline-flex items-center gap-2 text-xs text-neutral-500 disabled:opacity-20"><ArrowLeft size={14}/> Back</button><div className="hidden gap-2 sm:flex">{steps.map((_,n)=><span key={n} className={`h-1 rounded-full ${n<=i?"w-6 bg-amber-400":"w-2 bg-white/10"}`}/>)}</div>{i>0&&i<7?<button onClick={next} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-2.5 text-xs font-medium text-black">Continue <ArrowRight size={14}/></button>:<span className="text-[9px] uppercase tracking-[.2em] text-neutral-700">{i+1} / 8</span>}</div></div></main>;
}
